DROP TABLE SHIFT;
DROP TABLE SHIFT_GROUP;
DROP TABLE SHIFT_GROUPING;
CREATE TABLE SHIFT
( 
	ID VARCHAR2(50),
	CODE VARCHAR2(20) UNIQUE
);

CREATE TABLE SHIFT_GROUP
( 
	ID VARCHAR2(50),
	CODE VARCHAR2(20) UNIQUE
);

CREATE TABLE SHIFT_GROUPING
( 
	ID VARCHAR2(50),
	SHIFT_GROUP_CODE VARCHAR2(20),
	SHIFT_CODE VARCHAR2(20)
);


INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT1');
INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT2');
INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT3');
INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT4');
INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT5');
INSERT INTO SHIFT VALUES(SYS_GUID(),'SHIFT6');
INSERT INTO SHIFT_GROUP VALUES(SYS_GUID(),'SHIFT_GROUP1');
INSERT INTO SHIFT_GROUP VALUES(SYS_GUID(),'SHIFT_GROUP2');
INSERT INTO SHIFT_GROUP VALUES(SYS_GUID(),'SHIFT_GROUP3');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP1','SHIFT1');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP1','SHIFT2');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP1','SHIFT3');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP2','SHIFT4');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP2','SHIFT5');
INSERT INTO SHIFT_GROUPING VALUES(SYS_GUID(),'SHIFT_GROUP3','SHIFT6');
